import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import styles2 from "@/styles/suggestions.module.scss";
import Link from "next/link";
import React from "react";
import { SuggestionsCtx } from "@/context";
import Popup from "./popup";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { suggestions, setSuggestions } = React.useContext(SuggestionsCtx);

  const [filter, setFilter] = React.useState("");
  const [openPopup, setopenPopup] = React.useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.sidebar}>
          <div className={styles.feedBoard}>
            <div className={styles.txt1}>
              <text>Frontend Mentor</text>
              <p>Feedback Board</p>
            </div>
            <div
              onClick={() => setopenPopup(!openPopup)}
              className={openPopup ? styles.menux : styles.menu}
            ></div>
          </div>
          <div className={styles.sideOptions}>
            <div className={styles.lineCont}>
              <div className={styles.line}>
                <div
                  onClick={() => {
                    setFilter("");
                  }}
                  className={styles.btn1}
                  style={{
                    backgroundColor: filter == "" ? "#4661e6" : "#f2f4ff",
                    color: filter == "" ? "#ffffff" : "#4661e6",
                  }}
                >
                  All
                </div>
                <div
                  onClick={() => {
                    setFilter("UI");
                  }}
                  className={styles.btn2}
                  style={{
                    backgroundColor: filter == "UI" ? "#4661e6" : "#f2f4ff",
                    color: filter == "UI" ? "#ffffff" : "#4661e6",
                  }}
                >
                  UI
                </div>
                <div
                  onClick={() => {
                    setFilter("UX");
                  }}
                  className={styles.btn3}
                  style={{
                    backgroundColor: filter == "UX" ? "#4661e6" : "#f2f4ff",
                    color: filter == "UX" ? "#ffffff" : "#4661e6",
                  }}
                >
                  UX
                </div>
              </div>
              <div className={styles.line2}>
                <div
                  onClick={() => {
                    setFilter("Enhancement");
                  }}
                  className={styles.btn4}
                  style={{
                    backgroundColor:
                      filter == "Enhancement" ? "#4661e6" : "#f2f4ff",
                    color: filter == "Enhancement" ? "#ffffff" : "#4661e6",
                  }}
                >
                  Enhancement
                </div>
                <div
                  onClick={() => {
                    setFilter("Bug");
                  }}
                  className={styles.btn5}
                  style={{
                    backgroundColor: filter == "Bug" ? "#4661e6" : "#f2f4ff",
                    color: filter == "Bug" ? "#ffffff" : "#4661e6",
                  }}
                >
                  Bug
                </div>
              </div>
              <div className={styles.line}>
                <div
                  onClick={() => {
                    setFilter("Feature");
                  }}
                  className={styles.btn6}
                  style={{
                    backgroundColor:
                      filter == "Feature" ? "#4661e6" : "#f2f4ff",
                    color: filter == "Feature" ? "#ffffff" : "#4661e6",
                  }}
                >
                  Feature
                </div>
              </div>
            </div>
          </div>
          <div className={styles.roadMap}>
            <div className={styles.line3}>
              <text>Roadmap</text>
              <Link href="/roadmap">View</Link>
            </div>
            <div className={styles.line4}>
              <div className={styles.txt2}>
                <div className={styles.dotCont}>
                  <div className={styles.dot1}></div>
                  <p>Planned</p>
                </div>
                <text>0</text>
              </div>
              <div className={styles.txt3}>
                <div className={styles.dotCont}>
                  <div className={styles.dot2}></div>
                  <p>In-Progress</p>
                </div>
                <text>0</text>
              </div>
              <div className={styles.txt4}>
                <div className={styles.dotCont}>
                  <div className={styles.dot3}></div>
                  <p>Live</p>
                </div>
                <text>0</text>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.sidebar2}>
          <div className={styles.suggestion}>
            <div className={styles.leftside}>
              <div className={styles.img1}></div>{" "}
              <text>{suggestions?.length} Suggestions</text>
              <div className={styles.label}>
                <label>Sort by :</label>
                <select className={styles.sortby} id="sortby">
                  <option value="Most Upvotes">Most Upvotes</option>
                  <option value="Least Upvotes">Least Upvotes</option>
                  <option value="Most Comments">Most Comments</option>
                  <option value="Least Comments">Least Comments</option>
                </select>
              </div>
            </div>
            <Link href={"/feedback-new"}>
              {" "}
              <button className={styles.btn7}>+ Add Feedback</button>
            </Link>
          </div>
          {suggestions?.length > 0 ? (
            suggestions
              ?.filter((item) => {
                return item?.category.includes(filter);
              })
              .map((item, index) => {
                console.log(item);
                return (
                  <div className={styles2.sugSpace}>
                    <div className={styles2.topic}>
                      <button className={styles2.btn8}>
                        <span></span>
                        {item?.upvoates}
                      </button>
                      <div className={styles2.txt}>
                        <Link href={"/feedback-detail/?id=" + item?.id}>
                          <text>{item?.title}</text>
                        </Link>
                        <p>{item?.details}</p>
                        <button className={styles2.btn9}>
                          {item?.category}
                        </button>
                      </div>

                      <div className={styles2.chat}>
                        <span></span> {item?.comments?.length}
                      </div>
                      <div className={styles2.chat2}>
                        <button className={styles2.btn10}>
                          <span></span>99
                        </button>
                        <div className={styles2.chat1}>
                          <span></span>0
                        </div>
                      </div>
                    </div>
                  </div>
                );
              })
          ) : (
            <div className={styles.sugSpace}>
              <div className={styles.img2}></div>
              <text>There is no feedback yet.</text>
              <p>
                Got a suggestion? Found a bug that needs to be squashed?
                <br></br> We love hearing about new ideas to improve our app.
              </p>
              <Link href="/feedback-new">
                <button className={styles.btn8}>+ Add Feedback</button>
              </Link>
            </div>
          )}
        </div>
      </main>
      {openPopup && (
        <div className={styles.popup}>
          <Popup />
        </div>
      )}
    </div>
  );
}
