import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/popup.module.scss";
import Link from "next/link";
import React from "react";
import { SuggestionsCtx } from "@/context";

const inter = Inter({ subsets: ["latin"] });

export default function Popup() {
  const [filter, setFilter] = React.useState("");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.sidebar}>
          <div className={styles.sideOptions}>
            <div className={styles.lineCont}>
              <div className={styles.line}>
                <div
                  onClick={() => {
                    setFilter("");
                  }}
                  className={styles.btn1}
                  style={{
                    backgroundColor: filter == "" ? "#4661e6" : "#f2f4ff",
                    color: filter == "" ? "#ffffff" : "#4661e6",
                  }}
                >
                  All
                </div>
                <div
                  onClick={() => {
                    setFilter("UI");
                  }}
                  className={styles.btn2}
                  style={{
                    backgroundColor: filter == "UI" ? "#4661e6" : "#f2f4ff",
                    color: filter == "UI" ? "#ffffff" : "#4661e6",
                  }}
                >
                  UI
                </div>
                <div
                  onClick={() => {
                    setFilter("UX");
                  }}
                  className={styles.btn3}
                  style={{
                    backgroundColor: filter == "UX" ? "#4661e6" : "#f2f4ff",
                    color: filter == "UX" ? "#ffffff" : "#4661e6",
                  }}
                >
                  UX
                </div>
              </div>
              <div className={styles.line2}>
                <div
                  onClick={() => {
                    setFilter("Enhancement");
                  }}
                  className={styles.btn4}
                  style={{
                    backgroundColor:
                      filter == "Enhancement" ? "#4661e6" : "#f2f4ff",
                    color: filter == "Enhancement" ? "#ffffff" : "#4661e6",
                  }}
                >
                  Enhancement
                </div>
                <div
                  onClick={() => {
                    setFilter("Bug");
                  }}
                  className={styles.btn5}
                  style={{
                    backgroundColor: filter == "Bug" ? "#4661e6" : "#f2f4ff",
                    color: filter == "Bug" ? "#ffffff" : "#4661e6",
                  }}
                >
                  Bug
                </div>
              </div>
              <div className={styles.line}>
                <div
                  onClick={() => {
                    setFilter("Feature");
                  }}
                  className={styles.btn6}
                  style={{
                    backgroundColor:
                      filter == "Feature" ? "#4661e6" : "#f2f4ff",
                    color: filter == "Feature" ? "#ffffff" : "#4661e6",
                  }}
                >
                  Feature
                </div>
              </div>
            </div>
          </div>
          <div className={styles.roadMap}>
            <div className={styles.line3}>
              <text>Roadmap</text>
              <Link href="/roadmap">View</Link>
            </div>
            <div className={styles.line4}>
              <div className={styles.txt2}>
                <div className={styles.dotCont}>
                  <div className={styles.dot1}></div>
                  <p>Planned</p>
                </div>
                <text>0</text>
              </div>
              <div className={styles.txt3}>
                <div className={styles.dotCont}>
                  <div className={styles.dot2}></div>
                  <p>In-Progress</p>
                </div>
                <text>0</text>
              </div>
              <div className={styles.txt4}>
                <div className={styles.dotCont}>
                  <div className={styles.dot3}></div>
                  <p>Live</p>
                </div>
                <text>0</text>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
