import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/roadmap.module.scss";
import React from "react";
import { useRouter } from "next/router";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const [page, setPage] = React.useState([1]);

  React.useEffect(() => {
    let size = window.innerWidth;
    console.log(size);
    if (size > 400) {
      setPage([1, 2, 3]);
      console.log(page);
      return;
    }

    setPage([1]);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.cont}>
          <nav className={styles.nav}>
            <div className={styles.back}>
              <div onClick={() => router.back()} className={styles.bac}>
                <span></span>Go Back
              </div>
              <text>Roadmap</text>
            </div>
            <Link href="/feedback-new">
              {" "}
              <button className={styles.btn}>+ Add Feedback</button>
            </Link>
          </nav>
          <div className={styles.heder}>
            <div
              className={styles.one}
              onClick={() => {
                setPage([1]);
              }}
              style={{
                borderBottom: page[0] == 1 ? "#f49f85 3px solid" : "none",
              }}
            >
              Planned (2)
            </div>
            <div
              className={styles.two}
              onClick={() => {
                setPage([2]);
              }}
              style={{
                borderBottom: page[0] == 2 ? "#ad1fea 3px solid" : "none",
              }}
            >
              In-Progress (3)
            </div>
            <div
              className={styles.three}
              onClick={() => {
                setPage([3]);
              }}
              style={{
                borderBottom: page[0] == 3 ? "#62bcfa 3px solid" : "none",
              }}
            >
              Live (1)
            </div>
          </div>
          <div className={styles.map}>
            {page.includes(1) ? (
              <div className={styles.planned}>
                <div className={styles.header}>
                  <text>Planned (2)</text>
                  <p>Ideas prioritized for research</p>
                </div>
                <div className={styles.content}>
                  <div className={styles.dotCont}>
                    <div className={styles.dot1}></div>
                    <p>Planned</p>
                  </div>
                  <div className={styles.info}>
                    <text>More comprehensive reports</text>
                    <p>
                      It would be great to see a more detailed breakdown of
                      solutions.
                    </p>
                  </div>
                  <button className={styles.btn2}>Feature</button>
                  <div className={styles.upvoteCont}>
                    <button className={styles.upvote}>
                      <span></span>123
                    </button>
                    <div className={styles.comment}>
                      <span></span>2
                    </div>
                  </div>
                </div>
                <div className={styles.content}>
                  <div className={styles.dotCont}>
                    <div className={styles.dot1}></div>
                    <p>Planned</p>
                  </div>
                  <div className={styles.info}>
                    <text>Learning paths</text>
                    <p>
                      Sequenced projects for different goals to help people
                      improve.
                    </p>
                  </div>
                  <button className={styles.btn2}>Feature</button>
                  <div className={styles.upvoteCont}>
                    <button className={styles.upvote}>
                      <span></span>28
                    </button>
                    <div className={styles.comment}>
                      <span></span>1
                    </div>
                  </div>
                </div>
              </div>
            ) : null}
            {page.includes(2) ? (
              <div className={styles.inprogress}>
                <div className={styles.header}>
                  <text>In-Progress (3)</text>
                  <p>Currently being developed</p>
                </div>
                <div className={styles.content2}>
                  <div className={styles.dotCont}>
                    <div className={styles.dot2}></div>
                    <p>In Progress</p>
                  </div>
                  <div className={styles.info}>
                    <text>One-click portfolio generation</text>
                    <p>
                      Add ability to create professional looking portfolio from
                      profile.
                    </p>
                  </div>
                  <button className={styles.btn2}>Feature</button>
                  <div className={styles.upvoteCont}>
                    <button className={styles.upvote}>
                      <span></span>123
                    </button>
                    <div className={styles.comment}>
                      <span></span>2
                    </div>
                  </div>
                </div>
                <div className={styles.content2}>
                  <div className={styles.dotCont}>
                    <div className={styles.dot2}></div>
                    <p>In Progress</p>
                  </div>
                  <div className={styles.info}>
                    <text>Bookmark challenges</text>
                    <p>Be able to bookmark challenges to take later on.</p>
                  </div>
                  <button className={styles.btn2}>Feature</button>
                  <div className={styles.upvoteCont}>
                    <button className={styles.upvote}>
                      <span></span>28
                    </button>
                    <div className={styles.comment}>
                      <span></span>1
                    </div>
                  </div>
                </div>
                <div className={styles.content2}>
                  <div className={styles.dotCont}>
                    <div className={styles.dot2}></div>
                    <p>In Progress</p>
                  </div>
                  <div className={styles.info}>
                    <text>Animated solution screenshots</text>
                    <p>
                      Screenshots of solutions with animations don’t display
                      content.
                    </p>
                  </div>
                  <button className={styles.btn2}>Feature</button>
                  <div className={styles.upvoteCont}>
                    <button className={styles.upvote}>
                      <span></span>9
                    </button>
                    <div className={styles.comment}>
                      <span></span>0
                    </div>
                  </div>
                </div>
              </div>
            ) : null}
            {page.includes(3) ? (
              <div className={styles.live}>
                <div className={styles.header}>
                  <text>Live (1)</text>
                  <p>Released features</p>
                </div>
                <div className={styles.content3}>
                  <div className={styles.dotCont}>
                    <div className={styles.dot3}></div>
                    <p>Live</p>
                  </div>
                  <div className={styles.info}>
                    <text>Add micro-interactions</text>
                    <p>Small animations at specific points can add delight.</p>
                  </div>
                  <button className={styles.btn2}>Feature</button>
                  <div className={styles.upvoteCont}>
                    <button className={styles.upvote}>
                      <span></span>71
                    </button>
                    <div className={styles.comment}>
                      <span></span>2
                    </div>
                  </div>
                </div>
              </div>
            ) : null}
          </div>
        </div>
      </main>
    </div>
  );
}
